# Generated by Django 2.1 on 2018-08-10 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roboapp', '0004_book'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.AlterModelOptions(
            name='robot',
            options={'verbose_name': 'robot', 'verbose_name_plural': 'robots'},
        ),
        migrations.RemoveField(
            model_name='robot',
            name='password',
        ),
        migrations.RemoveField(
            model_name='robot',
            name='username',
        ),
        migrations.AddField(
            model_name='robot',
            name='book_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Hardcover'), (2, 'Paperback'), (3, 'E-book')], default=1),
        ),
        migrations.AddField(
            model_name='robot',
            name='mqttpass',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='robot',
            name='mqttuser',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='robot',
            name='robotname',
            field=models.CharField(default='', max_length=50),
        ),
    ]
