# Generated by Django 2.1 on 2018-08-11 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roboapp', '0006_book'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='authors',
        ),
        migrations.AddField(
            model_name='book',
            name='authors',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='roboapp.robot'),
        ),
    ]
