# Generated by Django 2.1 on 2018-08-11 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roboapp', '0008_auto_20180811_1001'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mqttbroker',
            options={'verbose_name': 'robot', 'verbose_name_plural': 'robots'},
        ),
    ]
