# Generated by Django 2.1 on 2018-08-11 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roboapp', '0009_auto_20180811_1008'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mqttbroker',
            options={'verbose_name': 'mqttbroker', 'verbose_name_plural': 'mqttbrokers'},
        ),
    ]
