# Generated by Django 2.1 on 2018-08-11 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roboapp', '0010_auto_20180811_1012'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mqttbroker',
            name='mqttrobot',
        ),
        migrations.AddField(
            model_name='mqttbroker',
            name='robots',
            field=models.ManyToManyField(to='roboapp.robot'),
        ),
    ]
