# Generated by Django 2.1 on 2018-08-11 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roboapp', '0011_auto_20180811_1018'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.AlterModelOptions(
            name='mqttbroker',
            options={},
        ),
        migrations.RemoveField(
            model_name='mqttbroker',
            name='robots',
        ),
        migrations.RemoveField(
            model_name='robot',
            name='book_type',
        ),
    ]
