# Generated by Django 2.1 on 2018-08-11 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roboapp', '0018_auto_20180811_1231'),
    ]

    operations = [
        migrations.RenameField(
            model_name='robot',
            old_name='user',
            new_name='author',
        ),
    ]
