# Generated by Django 2.1 on 2018-08-11 12:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roboapp', '0020_auto_20180811_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='robot',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
