# Generated by Django 2.1 on 2018-08-11 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roboapp', '0023_robot_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='robot',
            old_name='author',
            new_name='user',
        ),
    ]
