# Generated by Django 2.1 on 2018-08-11 13:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roboapp', '0027_auto_20180811_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='robot',
            name='user',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True),
        ),
    ]
