# Generated by Django 2.1 on 2018-08-11 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roboapp', '0029_auto_20180811_1348'),
    ]

    operations = [
        migrations.AddField(
            model_name='mqttbroker',
            name='apikey',
            field=models.CharField(default='0', help_text='Enter field documentation', max_length=40),
        ),
    ]
