# Generated by Django 2.1 on 2018-08-23 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roboapp', '0030_mqttbroker_apikey'),
    ]

    operations = [
        migrations.CreateModel(
            name='battle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gameongoing', models.BooleanField(default=True)),
                ('robotturn', models.CharField(default=' ', help_text='Robot ID of current robot turn', max_length=40)),
                ('current_turn', models.IntegerField(default=0, help_text='Turns taken so far')),
            ],
        ),
    ]
