# Generated by Django 2.1 on 2018-08-29 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roboapp', '0031_battle'),
    ]

    operations = [
        migrations.AddField(
            model_name='robot',
            name='camera_ip',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
