# Generated by Django 2.1 on 2018-08-29 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roboapp', '0032_robot_camera_ip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='robot',
            name='camera_ip',
            field=models.CharField(max_length=80, null=True),
        ),
    ]
