# Generated by Django 2.1 on 2018-09-10 19:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('roboapp', '0033_auto_20180829_1528'),
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('entry_cost', models.IntegerField(default=100)),
                ('arena', models.TextField(max_length=300, null=True)),
                ('name', models.TextField(max_length=300)),
                ('players', models.IntegerField(default=10)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('robot_name', models.CharField(max_length=80)),
                ('xp', models.IntegerField(default=0)),
                ('robotify_points', models.IntegerField(default=0)),
                ('level', models.IntegerField(default=0)),
                ('wins', models.IntegerField(default=0)),
                ('losses', models.IntegerField(default=0)),
                ('colour_choice', models.CharField(choices=[('#2e86de', 'Blue'), ('#ee5253', 'Red'), ('#1dd1a1', 'Green'), ('#5f27cd', 'Purple'), ('#f368e0', 'Pink'), ('#ff9f43', 'Orange')], default='#2e86de', max_length=20)),
                ('robicon_choice', models.CharField(choices=[('r1blue.png', 'Blue 1'), ('r2blue.png', 'Blue 2'), ('r3blue.png', 'Blue 3'), ('r1red.png', 'Red 1'), ('r2red.png', 'Red 2'), ('r3red.png', 'Red 3'), ('r1green.png', 'Green 1'), ('r2green.png', 'Green 2'), ('r3green.png', 'Green 3'), ('r1purple.png', 'Purple 1'), ('r2purple.png', 'Purple 2'), ('r3purple.png', 'Purple 3'), ('r1pink.png', 'Pink 1'), ('r2pink.png', 'Pink 2'), ('r3pink.png', 'Pink 3'), ('r1orange.png', 'Pink 1'), ('r2orange.png', 'Pink 2'), ('r3orange.png', 'Pink 3')], default='r1blue.png', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='competition',
            name='first_place',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_profile1', to='roboapp.UserProfile'),
        ),
        migrations.AddField(
            model_name='competition',
            name='second_place',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_profile2', to='roboapp.UserProfile'),
        ),
        migrations.AddField(
            model_name='competition',
            name='third_place',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_profile3', to='roboapp.UserProfile'),
        ),
    ]
