# Generated by Django 2.1 on 2018-09-10 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roboapp', '0034_auto_20180910_1953'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competition',
            name='players',
        ),
        migrations.AddField(
            model_name='competition',
            name='active_players',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='competition',
            name='player_limit',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='competition',
            name='player_link',
            field=models.ManyToManyField(to='roboapp.UserProfile'),
        ),
    ]
