# Generated by Django 2.1 on 2018-09-10 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roboapp', '0035_auto_20180910_2014'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='robotify_points',
            new_name='balance',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='colour_choice',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='robicon_choice',
        ),
    ]
