# Generated by Django 2.1 on 2018-09-10 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roboapp', '0036_auto_20180910_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='active_players',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='competition',
            name='player_link',
            field=models.ManyToManyField(blank=True, null=True, to='roboapp.UserProfile'),
        ),
    ]
